version: '3.8'

services:
  # Servicio para la base de datos Postgresql
  db:
    image: postgres:17.5
    container_name: postgres_db
    environment:
      POSTGRES_DB: dentali_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    volumes:
      - db_data:/var/lib/postgresql/data # Persistencia de datos para la DB
    ports:
      - "5433:5432" # Mapea el puerto de la DB al host (opcional, útil para acceder desde local)

  # Servicio para la aplicación Spring Boot
  api:
    build: . # Construye la imagen a partir de mi Dockerfile en el directorio actual
    container_name: springboot_api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dentali_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
    depends_on:
      - db # Asegura que el servicio 'db' se inicie antes que api
    restart: on-failure # Reinicia el servidor si Falla

volumes:
  db_data: # Define el volumen para la persistencia de la base de datos
